config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :people

  resources :products#, concerns: :paginatable

  resources :categories

  root "products#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  scope :search, ->(term) do
    if term.present?
      where("products.name like :term or description like :term or categories.name like :term", term:"%#{term}%").references(:categories)
    end
  end
  scope :order_column, ->(column, direction){ order("products.#{column}  #{direction}")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :company, :phone, :country, :state, :city, :zip, :street, :email)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.includes(:category).search(params[:search])
      .order_column(sort_param,direction_param)
      .page(params[:page]).per(5)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category_id, :price, :description)
    end

    def sort_param
      params[:sort].presence || 'name'
    end
    def direction_param
      params[:direction].presence || 'asc'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title){ page_title }
  end

  def sortable(column, title=nil)
    title ||= column.titleize
    direction = params[:direction] == 'desc' ? 'asc' : 'desc'
    # link_to title, sort:column, direction:direction, page:params[:page], remote:true
    link_to title, params.merge(sort:column, direction:direction, page:1), remote:true
  end
  def products_page_title
    params[:search].to_s.titleize +
        " Products by " +
        (params[:sort] || 'name').titleize +
        " - Page #{params[:page] || 1}"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for @category, :html => { :class => "form-horizontal" } do |f|
  -if @category.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"

      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/categories/edit.html.haml
.page-header
  = link_to categories_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @category, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing category

= render 'form'

app/views/categories/index.html.haml
.page-header
  = link_to new_category_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Category
  %h1 Listing categories

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
        %th
        %th

    %tbody
      - @categories.each do |category|
        %tr
          %td= category.name
          %td= link_to 'Show', category
          %td= link_to 'Edit', edit_category_path(category)
          %td= link_to 'Destroy', category, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/categories/new.html.haml
.page-header
  = link_to categories_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New category

= render 'form'

app/views/categories/show.html.haml
.page-header
  = link_to categories_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_category_path(@category), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show category

%dl.dl-horizontal
  %dt Name:
  %dd= @category.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title populate #{content_for?(:title) ? yield(:title) : "default"}
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => ".navbar-collapse"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to "Home", root_path
            %li
              = link_to "Category", categories_path
            %li
              = link_to "Products", products_path
            %li
              = link_to "People", people_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable" do
          %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
          = msg
      = yield

app/views/people/_form.html.haml
= form_for @person, :html => { :class => "form-horizontal" } do |f|
  -if @person.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"

      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :company, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :company, :class => 'form-control'
  .form-group
    = f.label :phone, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :phone, :class => 'form-control'
  .form-group
    = f.label :country, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :country, :class => 'form-control'
  .form-group
    = f.label :state, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :state, :class => 'form-control'
  .form-group
    = f.label :city, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :city, :class => 'form-control'
  .form-group
    = f.label :zip, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :zip, :class => 'form-control'
  .form-group
    = f.label :street, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :street, :class => 'form-control'
  .form-group
    = f.label :email, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :email, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/people/edit.html.haml
.page-header
  = link_to people_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @person, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing person

= render 'form'

app/views/people/index.html.haml
.page-header
  = link_to new_person_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Person
  %h1 Listing people

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Company
        %th Phone
        %th Country
        %th State
        %th City
        %th Zip
        %th Street
        %th Email
        %th
        %th
        %th

    %tbody
      - @people.each do |person|
        %tr
          %td= person.name
          %td= person.company
          %td= person.phone
          %td= person.country
          %td= person.state
          %td= person.city
          %td= person.zip
          %td= person.street
          %td= person.email
          %td= link_to 'Show', person
          %td= link_to 'Edit', edit_person_path(person)
          %td= link_to 'Destroy', person, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/people/new.html.haml
.page-header
  = link_to people_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New person

= render 'form'

app/views/people/show.html.haml
.page-header
  = link_to people_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_person_path(@person), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show person

%dl.dl-horizontal
  %dt Name:
  %dd= @person.name
  %dt Company:
  %dd= @person.company
  %dt Phone:
  %dd= @person.phone
  %dt Country:
  %dd= @person.country
  %dt State:
  %dd= @person.state
  %dt City:
  %dd= @person.city
  %dt Zip:
  %dd= @person.zip
  %dt Street:
  %dd= @person.street
  %dt Email:
  %dd= @person.email

app/views/products/_form.html.haml
= form_for @product, :html => { :class => "form-horizontal" } do |f|
  -if @product.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"

      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :category, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.collection_select :category, Category.all, :id, :name, :class => 'form-control'
  .form-group
    = f.label :price, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :price, :class => 'form-control'
  .form-group
    = f.label :description, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/products/_products.html.haml
= paginate @products, remote:true
= page_entries_info @products

= hidden_field_tag :page, params[:page]
= form_tag products_path, method:'get',remote:true do
  = text_field_tag :search, params[:search]
  = submit_tag "Search"

  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :direction, params[:direction]

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= sortable 'name'
        %th= sortable 'category'
        %th= sortable 'price'
        %th Description
        %th
        %th
        %th

    %tbody
      - @products.each do |product|
        %tr
          %td= product.name
          %td= product.category.name
          %td= product.price
          %td= product.description
          %td= link_to 'Show', product
          %td= link_to 'Edit', edit_product_path(product)
          %td= link_to 'Destroy', product, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/products/edit.html.haml
.page-header
  = link_to products_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @product, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing product

= render 'form'

app/views/products/index.html.haml
- title "Products"

.page-header
  = link_to new_product_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Product
  %h1 Listing products

#products
  = render 'products'

app/views/products/new.html.haml
.page-header
  = link_to products_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New product

= render 'form'

app/views/products/show.html.haml
.page-header
  = link_to products_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_product_path(@product), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show product

%dl.dl-horizontal
  %dt Name:
  %dd= @product.name
  %dt Category:
  %dd= @product.category.name
  %dt Price:
  %dd= @product.price
  %dt Description:
  %dd= @product.description